version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ai-tutor
      - LLaMA_API_KEY=${LLAMA_API_KEY}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    depends_on:
      - mongodb
    networks:
      - tutor-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tutor-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tutor-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - tutor-network

volumes:
  mongodb_data:

networks:
  tutor-network:
    driver: bridge
